version: '3'
services:
  todoo:
    image: klemjul/todoo:phttps
    ports:
      - "8000:8000"
    networks:
      todoonet:
        ipv4_address: 172.30.0.4
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todoo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root2'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /storage/docker/todoo/dump:/docker-entrypoint-initdb.d
      - /storage/docker/todoo/db:/var/lib/mysql
    networks:
      todoonet:
        ipv4_address: 172.30.0.6


  web:
    ports:
      - '4200:4200'
    image: klemjul/todooweb:phttps
    networks:
      todoonet:
        ipv4_address: 172.30.0.5
networks:
  todoonet:
    ipam:
      driver: default
      config: 
        - subnet: 172.30.0.0/16
