version: '3'
services:
  todoo:
    image: klemjul/todooweb:latest
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /home/root2/todoo:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todoo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root2'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /home/root2/data/dump:/docker-entrypoint-initdb.d
      - /home/root2/data/db:/var/lib/mysql
  web:
    ports:
      - '4200:4200'
    image: klemjul/todoo:dev
